import React,{useState} from 'react';
import { api } from '../utils/api';
import { formatLempiras } from '../utils/format';
import '../pages/OperacionesPage.css';
export const ProductoGestion:React.FC<{productos:any[];onSaved:()=>Promise<void>}> = ({productos,onSaved})=>{
 const [selected,setSelected]=useState<any>(null),[form,setForm]=useState<any>({}),[history,setHistory]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const choose=(id:string)=>{const p=productos.find(p=>p.id===id);setSelected(p||null);setForm(p?{...p,motivo:'',codigoBarras:p.codigoBarras||'',codigoFabricante:p.codigoFabricante||'',descripcion:p.descripcion||''}:{});setHistory(null);setError('');};
 return <section className="operation-card"><h2>Administrar producto y revisar movimientos</h2><label>Producto<select className="form-input" disabled={busy} value={selected?.id||''} onChange={e=>choose(e.target.value)}><option value="">Seleccione para editar</option>{productos.map(p=><option key={p.id} value={p.id}>{p.codigo} · {p.nombre}</option>)}</select></label>
 {error&&<p role="alert" className="operation-error">{error}</p>}
 {selected&&<><form className="operation-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const payload:any={codigo:form.codigo,nombre:form.nombre,codigoBarras:form.codigoBarras,codigoFabricante:form.codigoFabricante,descripcion:form.descripcion,motivo:form.motivo};for(const f of ['precioCosto','precioVenta','stockActual','stockMinimo'])payload[f]=Number(form[f]);await api.put(`/productos/${selected.id}`,payload);await onSaved();setSelected(null);setHistory(null);}catch(e:any){setError(e.response?.data?.message||'No se pudo guardar');}finally{setBusy(false);}}}>
 {(['codigo','nombre','codigoBarras','codigoFabricante','descripcion','precioCosto','precioVenta','stockActual','stockMinimo','motivo'] as const).map(k=><label key={k}>{{codigo:'Código interno',nombre:'Nombre y variante',codigoBarras:'Código de barras',codigoFabricante:'Código fabricante',descripcion:'Descripción',precioCosto:'Costo vigente',precioVenta:'Precio vigente de venta',stockActual:'Existencias',stockMinimo:'Stock mínimo',motivo:'Motivo del ajuste de existencias'}[k]}<input className="form-input" disabled={busy} required={['codigo','nombre'].includes(k)||k==='motivo'&&Number(form.stockActual)!==Number(selected.stockActual)} type={['precioCosto','precioVenta','stockActual','stockMinimo'].includes(k)?'number':'text'} min="0" step="0.01" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
 <button className="btn btn-primary" disabled={busy}>Guardar cambios</button></form><button className="btn btn-secondary" disabled={busy} onClick={async()=>{setBusy(true);try{setHistory((await api.get(`/operaciones/productos/${selected.id}/historial`)).data);}catch(e:any){setError(e.response?.data?.message||'No se pudo consultar');}finally{setBusy(false);}}}>Ver movimientos y costos por proveedor</button></>}
 {history&&<><h3>Movimientos</h3><div className="operation-table"><table><thead><tr><th>Fecha</th><th>Origen</th><th>Antes</th><th>Cambio</th><th>Después</th><th>Usuario / motivo</th></tr></thead><tbody>{history.movimientos.map((m:any)=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString('es-HN')}</td><td>{m.tipo}</td><td>{Number(m.anterior)}</td><td>{Number(m.cantidad)}</td><td>{Number(m.nuevo)}</td><td>{m.usuario_nombre} · {m.motivo}</td></tr>)}</tbody></table></div><h3>Compras por proveedor</h3><ul>{history.costos.map((c:any)=><li key={c.id}>{new Date(c.fecha).toLocaleString('es-HN')} · {c.proveedor_nombre} · Factura {c.numero_factura} · {Number(c.cantidad)} × {formatLempiras(Number(c.costo))}</li>)}</ul></>}
 </section>;
};
