-- NEXUS — auditoría de referencias entre empresas distintas (SOLO LECTURA).
-- 48 comprobaciones: FK de una columna entre tablas con tenant_id, comparaciones padre-padre para líneas de detalle sin tenant_id
-- y una de dos saltos (detalles_devolucion). Generado desde pg_constraint de la base combinada (18 migraciones).
-- Las comprobaciones cuyas tablas aún no existen en la base consultada se OMITEN (filas = NULL): sirve con 13 o con 18 migraciones.
-- La base no impide estos casos: solo coberturas_garantia tiene trigger de coherencia de tenant.
-- Resultado esperado: filas_con_tenant_distinto = 0 (o NULL si se omitió). Filtro útil: awk -F'|' '$3>0'. No modifica nada.

BEGIN READ ONLY;
SET LOCAL statement_timeout = '120s';

WITH checks(restriccion, relacion, tablas, consulta) AS MATERIALIZED (VALUES
  ('abonos_cliente_cliente_id_fkey', 'abonos_cliente.cliente_id -> clientes.id', ARRAY['abonos_cliente','clientes'], $q$SELECT count(*) AS c FROM "abonos_cliente" h JOIN "clientes" p ON p."id" = h."cliente_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('abonos_cliente_venta_id_fkey', 'abonos_cliente.venta_id -> ventas.id', ARRAY['abonos_cliente','ventas'], $q$SELECT count(*) AS c FROM "abonos_cliente" h JOIN "ventas" p ON p."id" = h."venta_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('apartados_cliente_id_fkey', 'apartados.cliente_id -> clientes.id', ARRAY['apartados','clientes'], $q$SELECT count(*) AS c FROM "apartados" h JOIN "clientes" p ON p."id" = h."cliente_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('apartados_producto_id_fkey', 'apartados.producto_id -> productos.id', ARRAY['apartados','productos'], $q$SELECT count(*) AS c FROM "apartados" h JOIN "productos" p ON p."id" = h."producto_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('aprobaciones_bancarias_usuario_fkey', 'aprobaciones_bancarias.usuario_id -> usuarios.id', ARRAY['aprobaciones_bancarias','usuarios'], $q$SELECT count(*) AS c FROM "aprobaciones_bancarias" h JOIN "usuarios" p ON p."id" = h."usuario_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('cajas_usuario_id_fkey', 'cajas.usuario_id -> usuarios.id', ARRAY['cajas','usuarios'], $q$SELECT count(*) AS c FROM "cajas" h JOIN "usuarios" p ON p."id" = h."usuario_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('cierres_comisiones_vendedor_id_fkey', 'cierres_comisiones.vendedor_id -> usuarios.id', ARRAY['cierres_comisiones','usuarios'], $q$SELECT count(*) AS c FROM "cierres_comisiones" h JOIN "usuarios" p ON p."id" = h."vendedor_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('clientes_lista_precio_id_fkey', 'clientes.lista_precio_id -> listas_precio.id', ARRAY['clientes','listas_precio'], $q$SELECT count(*) AS c FROM "clientes" h JOIN "listas_precio" p ON p."id" = h."lista_precio_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('coberturas_garantia_actualizado_fkey', 'coberturas_garantia.actualizado_por -> usuarios.id', ARRAY['coberturas_garantia','usuarios'], $q$SELECT count(*) AS c FROM "coberturas_garantia" h JOIN "usuarios" p ON p."id" = h."actualizado_por" WHERE h.tenant_id <> p.tenant_id$q$),
  ('coberturas_garantia_creado_fkey', 'coberturas_garantia.creado_por -> usuarios.id', ARRAY['coberturas_garantia','usuarios'], $q$SELECT count(*) AS c FROM "coberturas_garantia" h JOIN "usuarios" p ON p."id" = h."creado_por" WHERE h.tenant_id <> p.tenant_id$q$),
  ('coberturas_garantia_producto_fkey', 'coberturas_garantia.producto_id -> productos.id', ARRAY['coberturas_garantia','productos'], $q$SELECT count(*) AS c FROM "coberturas_garantia" h JOIN "productos" p ON p."id" = h."producto_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('coberturas_garantia_venta_fkey', 'coberturas_garantia.venta_id -> ventas.id', ARRAY['coberturas_garantia','ventas'], $q$SELECT count(*) AS c FROM "coberturas_garantia" h JOIN "ventas" p ON p."id" = h."venta_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('compras_proveedor_proveedor_id_fkey', 'compras_proveedor.proveedor_id -> proveedores.id', ARRAY['compras_proveedor','proveedores'], $q$SELECT count(*) AS c FROM "compras_proveedor" h JOIN "proveedores" p ON p."id" = h."proveedor_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('conciliaciones_bancarias_usuario_fkey', 'conciliaciones_bancarias.usuario_id -> usuarios.id', ARRAY['conciliaciones_bancarias','usuarios'], $q$SELECT count(*) AS c FROM "conciliaciones_bancarias" h JOIN "usuarios" p ON p."id" = h."usuario_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('contingencia_ventanas_dispositivo_fkey', 'contingencia_ventanas.dispositivo_id -> dispositivos_pos.id', ARRAY['contingencia_ventanas','dispositivos_pos'], $q$SELECT count(*) AS c FROM "contingencia_ventanas" h JOIN "dispositivos_pos" p ON p."id" = h."dispositivo_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('costos_compra_producto_id_fkey', 'costos_compra.producto_id -> productos.id', ARRAY['costos_compra','productos'], $q$SELECT count(*) AS c FROM "costos_compra" h JOIN "productos" p ON p."id" = h."producto_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('costos_compra_proveedor_id_fkey', 'costos_compra.proveedor_id -> proveedores.id', ARRAY['costos_compra','proveedores'], $q$SELECT count(*) AS c FROM "costos_compra" h JOIN "proveedores" p ON p."id" = h."proveedor_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('costos_compra_recepcion_id_fkey', 'costos_compra.recepcion_id -> recepciones_compra.id', ARRAY['costos_compra','recepciones_compra'], $q$SELECT count(*) AS c FROM "costos_compra" h JOIN "recepciones_compra" p ON p."id" = h."recepcion_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('cotizaciones_cliente_id_fkey', 'cotizaciones.cliente_id -> clientes.id', ARRAY['clientes','cotizaciones'], $q$SELECT count(*) AS c FROM "cotizaciones" h JOIN "clientes" p ON p."id" = h."cliente_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('cotizaciones_usuario_id_fkey', 'cotizaciones.usuario_id -> usuarios.id', ARRAY['cotizaciones','usuarios'], $q$SELECT count(*) AS c FROM "cotizaciones" h JOIN "usuarios" p ON p."id" = h."usuario_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('cotizaciones_venta_id_fkey', 'cotizaciones.venta_id -> ventas.id', ARRAY['cotizaciones','ventas'], $q$SELECT count(*) AS c FROM "cotizaciones" h JOIN "ventas" p ON p."id" = h."venta_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('cuentas_operativas_cliente_id_fkey', 'cuentas_operativas.cliente_id -> clientes.id', ARRAY['clientes','cuentas_operativas'], $q$SELECT count(*) AS c FROM "cuentas_operativas" h JOIN "clientes" p ON p."id" = h."cliente_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('cuentas_operativas_proveedor_id_fkey', 'cuentas_operativas.proveedor_id -> proveedores.id', ARRAY['cuentas_operativas','proveedores'], $q$SELECT count(*) AS c FROM "cuentas_operativas" h JOIN "proveedores" p ON p."id" = h."proveedor_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('devoluciones_venta_id_fkey', 'devoluciones.venta_id -> ventas.id', ARRAY['devoluciones','ventas'], $q$SELECT count(*) AS c FROM "devoluciones" h JOIN "ventas" p ON p."id" = h."venta_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('garantias_producto_id_fkey', 'garantias.producto_id -> productos.id', ARRAY['garantias','productos'], $q$SELECT count(*) AS c FROM "garantias" h JOIN "productos" p ON p."id" = h."producto_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('garantias_venta_id_fkey', 'garantias.venta_id -> ventas.id', ARRAY['garantias','ventas'], $q$SELECT count(*) AS c FROM "garantias" h JOIN "ventas" p ON p."id" = h."venta_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('movimientos_inventario_producto_id_fkey', 'movimientos_inventario.producto_id -> productos.id', ARRAY['movimientos_inventario','productos'], $q$SELECT count(*) AS c FROM "movimientos_inventario" h JOIN "productos" p ON p."id" = h."producto_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('operaciones_contingencia_dispositivo_fkey', 'operaciones_contingencia.dispositivo_id -> dispositivos_pos.id', ARRAY['dispositivos_pos','operaciones_contingencia'], $q$SELECT count(*) AS c FROM "operaciones_contingencia" h JOIN "dispositivos_pos" p ON p."id" = h."dispositivo_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('operaciones_contingencia_venta_fkey', 'operaciones_contingencia.venta_id -> ventas.id', ARRAY['operaciones_contingencia','ventas'], $q$SELECT count(*) AS c FROM "operaciones_contingencia" h JOIN "ventas" p ON p."id" = h."venta_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('operaciones_contingencia_ventana_fkey', 'operaciones_contingencia.ventana_id -> contingencia_ventanas.id', ARRAY['contingencia_ventanas','operaciones_contingencia'], $q$SELECT count(*) AS c FROM "operaciones_contingencia" h JOIN "contingencia_ventanas" p ON p."id" = h."ventana_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('ordenes_compra_proveedor_id_fkey', 'ordenes_compra.proveedor_id -> proveedores.id', ARRAY['ordenes_compra','proveedores'], $q$SELECT count(*) AS c FROM "ordenes_compra" h JOIN "proveedores" p ON p."id" = h."proveedor_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('ordenes_compra_usuario_id_fkey', 'ordenes_compra.usuario_id -> usuarios.id', ARRAY['ordenes_compra','usuarios'], $q$SELECT count(*) AS c FROM "ordenes_compra" h JOIN "usuarios" p ON p."id" = h."usuario_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('pagos_cuenta_cuenta_id_fkey', 'pagos_cuenta.cuenta_id -> cuentas_operativas.id', ARRAY['cuentas_operativas','pagos_cuenta'], $q$SELECT count(*) AS c FROM "pagos_cuenta" h JOIN "cuentas_operativas" p ON p."id" = h."cuenta_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('productos_categoria_id_fkey', 'productos.categoria_id -> categorias.id', ARRAY['categorias','productos'], $q$SELECT count(*) AS c FROM "productos" h JOIN "categorias" p ON p."id" = h."categoria_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('productos_proveedores_actualizado_fkey', 'productos_proveedores.actualizado_por -> usuarios.id', ARRAY['productos_proveedores','usuarios'], $q$SELECT count(*) AS c FROM "productos_proveedores" h JOIN "usuarios" p ON p."id" = h."actualizado_por" WHERE h.tenant_id <> p.tenant_id$q$),
  ('productos_proveedores_creado_fkey', 'productos_proveedores.creado_por -> usuarios.id', ARRAY['productos_proveedores','usuarios'], $q$SELECT count(*) AS c FROM "productos_proveedores" h JOIN "usuarios" p ON p."id" = h."creado_por" WHERE h.tenant_id <> p.tenant_id$q$),
  ('productos_proveedores_producto_fkey', 'productos_proveedores.producto_id -> productos.id', ARRAY['productos','productos_proveedores'], $q$SELECT count(*) AS c FROM "productos_proveedores" h JOIN "productos" p ON p."id" = h."producto_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('productos_proveedores_proveedor_fkey', 'productos_proveedores.proveedor_id -> proveedores.id', ARRAY['productos_proveedores','proveedores'], $q$SELECT count(*) AS c FROM "productos_proveedores" h JOIN "proveedores" p ON p."id" = h."proveedor_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('recepciones_compra_orden_id_fkey', 'recepciones_compra.orden_id -> ordenes_compra.id', ARRAY['ordenes_compra','recepciones_compra'], $q$SELECT count(*) AS c FROM "recepciones_compra" h JOIN "ordenes_compra" p ON p."id" = h."orden_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('transferencias_usuario_id_fkey', 'transferencias.usuario_id -> usuarios.id', ARRAY['transferencias','usuarios'], $q$SELECT count(*) AS c FROM "transferencias" h JOIN "usuarios" p ON p."id" = h."usuario_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('ventas_cliente_id_fkey', 'ventas.cliente_id -> clientes.id', ARRAY['clientes','ventas'], $q$SELECT count(*) AS c FROM "ventas" h JOIN "clientes" p ON p."id" = h."cliente_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('ventas_usuario_id_fkey', 'ventas.usuario_id -> usuarios.id', ARRAY['usuarios','ventas'], $q$SELECT count(*) AS c FROM "ventas" h JOIN "usuarios" p ON p."id" = h."usuario_id" WHERE h.tenant_id <> p.tenant_id$q$),
  ('par:detalles_compra_proveedor', 'detalles_compra_proveedor.compra_id -> compras_proveedor frente a detalles_compra_proveedor.producto_id -> productos', ARRAY['compras_proveedor','detalles_compra_proveedor','productos'], $q$SELECT count(*) AS c FROM "detalles_compra_proveedor" h JOIN "compras_proveedor" a ON a.id = h."compra_id" JOIN "productos" b ON b.id = h."producto_id" WHERE a.tenant_id <> b.tenant_id$q$),
  ('par:detalles_cotizacion', 'detalles_cotizacion.cotizacion_id -> cotizaciones frente a detalles_cotizacion.producto_id -> productos', ARRAY['cotizaciones','detalles_cotizacion','productos'], $q$SELECT count(*) AS c FROM "detalles_cotizacion" h JOIN "cotizaciones" a ON a.id = h."cotizacion_id" JOIN "productos" b ON b.id = h."producto_id" WHERE a.tenant_id <> b.tenant_id$q$),
  ('par:detalles_orden_compra', 'detalles_orden_compra.orden_id -> ordenes_compra frente a detalles_orden_compra.producto_id -> productos', ARRAY['detalles_orden_compra','ordenes_compra','productos'], $q$SELECT count(*) AS c FROM "detalles_orden_compra" h JOIN "ordenes_compra" a ON a.id = h."orden_id" JOIN "productos" b ON b.id = h."producto_id" WHERE a.tenant_id <> b.tenant_id$q$),
  ('par:detalles_transferencia', 'detalles_transferencia.producto_id -> productos frente a detalles_transferencia.transferencia_id -> transferencias', ARRAY['detalles_transferencia','productos','transferencias'], $q$SELECT count(*) AS c FROM "detalles_transferencia" h JOIN "productos" a ON a.id = h."producto_id" JOIN "transferencias" b ON b.id = h."transferencia_id" WHERE a.tenant_id <> b.tenant_id$q$),
  ('par:detalles_venta', 'detalles_venta.producto_id -> productos frente a detalles_venta.venta_id -> ventas', ARRAY['detalles_venta','productos','ventas'], $q$SELECT count(*) AS c FROM "detalles_venta" h JOIN "productos" a ON a.id = h."producto_id" JOIN "ventas" b ON b.id = h."venta_id" WHERE a.tenant_id <> b.tenant_id$q$),
  ('par:detalles_devolucion (2 saltos)', 'detalles_devolucion.devolucion_id -> devoluciones frente a detalles_venta -> ventas', ARRAY['detalles_devolucion','detalles_venta','devoluciones','ventas'], $q$SELECT count(*) AS c FROM "detalles_devolucion" h JOIN "devoluciones" a ON a.id = h.devolucion_id JOIN "detalles_venta" dv ON dv.id = h.detalle_venta_id JOIN "ventas" b ON b.id = dv.venta_id WHERE a.tenant_id <> b.tenant_id$q$)
)
SELECT restriccion, relacion,
  CASE WHEN NOT EXISTS (SELECT 1 FROM unnest(tablas) t WHERE to_regclass('public.'||t) IS NULL)
       THEN (xpath('/row/c/text()', query_to_xml(consulta, false, true, '')))[1]::text::int END AS filas_con_tenant_distinto
FROM checks
ORDER BY 3 DESC NULLS LAST, 1;

ROLLBACK;
