import { readFileSync, existsSync } from 'node:fs';
import { spawn } from 'node:child_process';
const password=readFileSync('/run/secrets/database_password','utf8').trim();
if(password.length<24)throw new Error('Configure una contraseña de base de datos de al menos 24 caracteres');
const host=process.env.DATABASE_HOST||'database';
if(!/^[a-zA-Z0-9.-]+$/.test(host))throw new Error('Host de base de datos inválido');
process.env.DATABASE_URL=`postgresql://ferresystem:${encodeURIComponent(password)}@${host}:5432/ferresystem`;
process.env.DIRECT_URL=process.env.DATABASE_URL;
process.env.PGHOST=host;process.env.PGPORT='5432';process.env.PGDATABASE='ferresystem';process.env.PGUSER='ferresystem';process.env.PGPASSWORD=password;
if(existsSync('/run/secrets/jwt_secret'))process.env.JWT_SECRET=readFileSync('/run/secrets/jwt_secret','utf8').trim();
const [command,...args]=process.argv.slice(2);
if(!command)throw new Error('Defina el comando del contenedor');
const child=spawn(command,args,{stdio:'inherit',env:process.env});
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>child.kill(signal));
child.on('error',()=>{console.error('No se pudo iniciar el servicio');process.exitCode=1;});
child.on('exit',(code)=>{process.exitCode=code??1;});
