import React,{useEffect,useState} from 'react';
import { TopBar } from '../components/TopBar';
import { useTenant } from '../context/TenantContext';
import { api } from '../utils/api';
import { formatInstanteNegocio } from '../utils/format';
import './OperacionesPage.css';
const names:Record<string,string>={VENTA_CREAR:'Venta registrada',VENTA_ENTREGAR:'Entrega',VENTA_DEVOLVER:'Devolución',COMPRA_CREAR:'Factura de proveedor',COMPRA_RECIBIR:'Recepción de compra',PROVEEDOR_CREAR:'Nuevo proveedor',CUENTA_PAGAR:'Abono o pago',CAJA_ABRIR:'Apertura de caja',CAJA_CERRAR:'Cierre de caja',PRODUCTO_CREAR:'Nuevo producto',PRODUCTO_EDITAR:'Producto modificado',PRODUCTO_DESACTIVAR:'Producto desactivado',STOCK_AJUSTAR:'Ajuste de existencias',CONTEO_CREAR:'Captura de conteo',CONTEO_EDITAR:'Corrección de conteo',CONTEO_ELIMINAR:'Conteo eliminado',LEVANTAMIENTO_ESTADO:'Estado del levantamiento',LEVANTAMIENTO_APLICAR:'Aplicación de inventario',LEVANTAMIENTO_ELIMINAR:'Levantamiento eliminado',USUARIO_CREAR:'Nuevo usuario',USUARIO_EDITAR:'Usuario o permisos modificados'};
export const AuditoriaPage:React.FC=()=>{
 const {tenant}=useTenant();const [page,setPage]=useState(0),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);setError('');api.get('/operaciones/auditoria',{params:{page}}).then(r=>{if(alive)setRows(r.data);}).catch(()=>{if(alive){setRows([]);setError('No se pudo consultar el historial');}}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[tenant.id,page,refresh]);
 return <div><TopBar title="AUDITORÍA" subtitle="Usuario, fecha y datos de cada operación registrada"/><main className="operation-page">{error&&<p role="alert" className="operation-error">{error}</p>}{loading&&<p role="status">Cargando…</p>}<div className="operation-actions"><button className="btn btn-secondary" disabled={loading||page===0} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page+1}</span><button className="btn btn-secondary" disabled={loading||rows.length<100} onClick={()=>setPage(page+1)}>Siguiente</button><button className="btn btn-secondary" disabled={loading} onClick={()=>setRefresh(r=>r+1)}>Actualizar</button></div><div className="operation-table operation-card"><table><thead><tr><th>Fecha</th><th>Usuario</th><th>Operación</th><th>Documento / detalle</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{formatInstanteNegocio(r.created_at)}</td><td>{r.usuario_nombre||r.usuario_id}</td><td>{names[r.operacion]||r.operacion}</td><td>{r.entidad_id}<details><summary>Datos registrados</summary><pre style={{whiteSpace:'pre-wrap',maxWidth:500}}>{JSON.stringify(r.datos,null,2)}</pre></details></td></tr>)}</tbody></table></div>{!loading&&!rows.length&&<p>Sin registros en esta página.</p>}</main></div>;
};
