import React, { useCallback, useEffect, useRef, useState } from 'react';
import { api } from '../utils/api';
import { TopBar } from '../components/TopBar';
import { useTenant } from '../context/TenantContext';
import { exportToCSV } from '../utils/csvExport';
import { exportToExcel } from '../utils/excelExport';
import './OperacionesPage.css';
import { BarcodeScanner } from '../components/BarcodeScanner';
import { readStoredJson } from '../utils/storage';
const blank=()=>({descripcion:'',cantidad:'1',unidad:'UNIDAD',codigo:'',codigoBarras:'',marca:'',categoria:'',ubicacion:'',precioCosto:'',precioVenta:'',margen:'',notas:''});
const message=(e:any)=>{const m=e.response?.data?.message;return Array.isArray(m)?m.join(', '):m||'No se pudo guardar. Revise la conexión y reintente.';};
export const LevantamientoPage:React.FC=()=>{
 const {tenant,user,isReadOnly}=useTenant();
 const [sessions,setSessions]=useState<any[]>([]),[activeId,setActiveId]=useState(''),[active,setActive]=useState<any>(null);
 const [nombre,setNombre]=useState(''),[form,setForm]=useState(blank()),[editing,setEditing]=useState<any>(null),[preview,setPreview]=useState<any>(null);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);const inFlight=useRef(false);
 const pendingKey=`ferre_pending_count:${tenant.id}:${user?.id}`;
 const [pendingCount,setPendingCount]=useState<any>(()=>readStoredJson(pendingKey,null));
 useEffect(()=>{setPendingCount(readStoredJson(pendingKey,null));},[pendingKey]);
 const closed=active?.estado==='FINALIZADO'||!!active?.aplicadoAt;
 const load=useCallback(async()=>{setLoading(true);try{setSessions((await api.get('/levantamientos')).data);if(activeId)setActive((await api.get(`/levantamientos/${activeId}`)).data);else setActive(null);}catch(e){setError(message(e));}finally{setLoading(false);}},[activeId,tenant.id]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{setActiveId('');setActive(null);setPreview(null);setEditing(null);setForm(blank());},[tenant.id]);
 const action=async(fn:()=>Promise<void>)=>{if(inFlight.current||isReadOnly)return;inFlight.current=true;setBusy(true);setError('');try{await fn();await load();}catch(e){setError(message(e));}finally{inFlight.current=false;setBusy(false);}};
 const sendCount=async(command:any)=>{try{await api.post(`/levantamientos/${command.lid}/items`,command.dto);}catch(e:any){if([400,404,409,422].includes(e.response?.status)){localStorage.removeItem(pendingKey);setPendingCount(null);}throw e;}localStorage.removeItem(pendingKey);setPendingCount(null);setForm(f=>({...blank(),unidad:f.unidad,ubicacion:f.ubicacion}));setPreview(null);};
 const exportRows=()=>active.items.map((i:any)=>({codigo:i.codigo||'',codigoBarras:i.codigoBarras||'',descripcion:i.descripcion,cantidad:Number(i.cantidad),unidad:i.unidad,categoria:i.categoria||'',costo:i.precioCosto??'',precio:i.precioVenta??'',margen:i.margen??'',ubicacion:i.ubicacion||'',marca:i.marca||'',notas:i.notas||''}));
 const set=(key:keyof ReturnType<typeof blank>,value:string)=>setForm(f=>({...f,[key]:value}));
 return <div><TopBar title="LEVANTAMIENTO DE INVENTARIO" subtitle="Conteo, revisión y aplicación al inventario"/><main className="operation-page">
  {error&&<div role="alert" className="operation-error">{error}</div>}{loading&&<p role="status">Cargando…</p>}
  {pendingCount&&<div className="operation-error" role="alert">Hay un conteo pendiente de confirmar. Reintente para consultar o guardar la misma operación.<button className="btn btn-secondary" disabled={busy||isReadOnly} onClick={()=>void action(async()=>{await sendCount(pendingCount);})}>Confirmar conteo pendiente</button></div>}
  <div className="operation-actions"><button className="btn btn-secondary" disabled={busy} onClick={()=>void load()}>Actualizar</button>{activeId&&<button className="btn btn-secondary" onClick={()=>{setActiveId('');setPreview(null);setEditing(null);setForm(blank());}}>Volver a levantamientos</button>}</div>
  {!activeId&&<><form className="operation-card operation-form" onSubmit={e=>{e.preventDefault();void action(async()=>{const r=await api.post('/levantamientos',{nombre});setNombre('');setActiveId(r.data.id);});}}><label>Nombre del levantamiento<input className="form-input" required value={nombre} disabled={busy||isReadOnly} onChange={e=>setNombre(e.target.value)}/></label><button className="btn btn-primary" disabled={busy||isReadOnly}>Crear levantamiento</button></form>{sessions.map(s=><button className="operation-card" style={{textAlign:'left'}} key={s.id} onClick={()=>{setActiveId(s.id);setPreview(null);}}><strong>{s.nombre}</strong> · {s.estado} · {s.totalItems} artículos {s.aplicadoAt&&'· Aplicado'}</button>)}</>}
  {active&&<><section className="operation-card"><h2>{active.nombre} · {active.estado}</h2>{active.aplicadoAt?<p>Aplicado al inventario el {new Date(active.aplicadoAt).toLocaleString('es-HN')}. El conteo original se conserva.</p>:<p>Finalizar cierra el conteo. Aplicar al inventario es una acción separada del administrador.</p>}<div className="operation-actions">
   {!closed&&<button className="btn btn-secondary" disabled={busy||isReadOnly||!active.items.length} onClick={()=>{if(window.confirm('¿Finalizar este conteo sin modificar inventario todavía?'))void action(async()=>{await api.patch(`/levantamientos/${activeId}`,{estado:'FINALIZADO'});});}}>Finalizar conteo</button>}
   {active.estado==='FINALIZADO'&&!active.aplicadoAt&&user?.rol==='ADMIN'&&<button className="btn btn-secondary" disabled={busy||isReadOnly} onClick={()=>void action(async()=>{await api.patch(`/levantamientos/${activeId}`,{estado:'REVISION'});setPreview(null);})}>Reabrir para conciliar</button>}
   {!active.aplicadoAt&&<button className="btn btn-primary" disabled={busy||isReadOnly} onClick={()=>void action(async()=>{setPreview((await api.get(`/levantamientos/${activeId}/preview`)).data);})}>Revisar impacto en inventario</button>}
   <button className="btn btn-secondary" disabled={!active.items.length} onClick={()=>{const rows=exportRows();exportToCSV(`levantamiento_${active.id}.csv`,rows,Object.keys(rows[0]).map(key=>({key,label:key})));}}>Exportar CSV</button>
   <button className="btn btn-secondary" disabled={!active.items.length} onClick={()=>exportToExcel(`levantamiento_${active.id}`,exportRows())}>Exportar Excel</button>
  </div></section>
  {!closed&&<form className="operation-card" onSubmit={e=>{e.preventDefault();void action(async()=>{
   const dto:any={...form,cantidad:Number(form.cantidad),codigo:form.codigo||undefined,codigoBarras:form.codigoBarras||undefined};
   for(const key of ['precioCosto','precioVenta','margen'] as const)dto[key]=form[key]===''?undefined:Number(form[key]);
   if(editing)await api.patch(`/levantamientos/${activeId}/items/${editing.id}`,{...dto,version:editing.version});else {if(pendingCount)throw new Error('Confirme el conteo pendiente');const command={lid:activeId,dto:{...dto,solicitudId:crypto.randomUUID()}};localStorage.setItem(pendingKey,JSON.stringify(command));setPendingCount(command);await sendCount(command);}
   setForm(f=>({...blank(),unidad:f.unidad,ubicacion:f.ubicacion}));setEditing(null);setPreview(null);
  });}}><BarcodeScanner disabled={busy||isReadOnly||!!pendingCount} onCode={code=>set('codigoBarras',code)}/><h2>{editing?'Corregir conteo':'Contar producto'}</h2><fieldset disabled={busy||isReadOnly||!!pendingCount} className="operation-form">
   <label>Descripción y variante<input className="form-input" required value={form.descripcion} onChange={e=>set('descripcion',e.target.value)} placeholder="Tipo, medida, espesor, color…"/></label><label>Cantidad<input className="form-input" type="number" min="0" step="0.01" required value={form.cantidad} onChange={e=>set('cantidad',e.target.value)}/></label><label>Unidad<select className="form-input" value={form.unidad} onChange={e=>set('unidad',e.target.value)}>{['UNIDAD','PIE','METRO','METRO_CUADRADO','METRO_CUBICO','LIBRA','KG','GALON','LITRO','CAJA','PAQUETE','OTRO'].map(u=><option key={u}>{u}</option>)}</select></label>
   {(['codigo','codigoBarras','marca','categoria','ubicacion','precioCosto','precioVenta','margen','notas'] as const).map(key=><label key={key}>{{codigo:'Código interno o fabricante (opcional)',codigoBarras:'Código de barras (opcional)',marca:'Marca',categoria:'Categoría',ubicacion:'Zona o ubicación',precioCosto:'Costo',precioVenta:'Precio de venta',margen:'Margen %',notas:'Notas'}[key]}<input className="form-input" type={['precioCosto','precioVenta','margen'].includes(key)?'number':'text'} min="0" step="0.01" max={key==='margen'?100:undefined} value={form[key]} onChange={e=>set(key,e.target.value)}/></label>)}
  </fieldset><p>Si el producto es nuevo, complete costo y precio antes de aplicar. Los artículos sin código recibirán uno interno.</p><button className="btn btn-primary" disabled={busy||isReadOnly||!!pendingCount}>Guardar y siguiente</button>{editing&&<button className="btn btn-secondary" type="button" onClick={()=>{setEditing(null);setForm(blank());}}>Cancelar corrección</button>}</form>}
  <div className="operation-table operation-card"><table><thead><tr><th>Producto</th><th>Código</th><th>Cantidad</th><th>Zona</th><th>Costo / precio</th><th>Acciones</th></tr></thead><tbody>{active.items.map((i:any)=><tr key={i.id}><td>{i.descripcion}</td><td>{i.codigo||i.codigoBarras||'Sin código'}</td><td>{Number(i.cantidad)} {i.unidad}</td><td>{i.ubicacion}</td><td>{i.precioCosto??'—'} / {i.precioVenta??'—'}</td><td>{!closed&&<><button disabled={busy||isReadOnly} onClick={()=>{setEditing(i);setForm(Object.fromEntries(Object.keys(blank()).map(k=>[k,i[k]==null?'':String(i[k])])) as ReturnType<typeof blank>);}}>Corregir</button><button disabled={busy||isReadOnly} onClick={()=>{if(window.confirm('¿Eliminar este conteo?'))void action(async()=>{await api.delete(`/levantamientos/${activeId}/items/${i.id}`,{params:{version:i.version}});setPreview(null);});}}>Eliminar</button></>}</td></tr>)}</tbody></table></div>
  {preview&&<section className="operation-card"><h2>Vista previa de aplicación</h2><p>Las cantidades revisadas sustituirán las existencias indicadas. Si cambia el inventario, será necesario revisar nuevamente.</p><div className="operation-table"><table><thead><tr><th>Producto</th><th>Antes</th><th>Conteo</th><th>Revisión</th></tr></thead><tbody>{preview.rows.map((r:any)=><tr key={r.item.id}><td>{r.codigo} · {r.nombre}</td><td>{r.anterior}</td><td>{r.nuevo}</td><td>{r.errores.length?r.errores.join('; '):r.productoId?'Actualizar existente':'Crear producto'}</td></tr>)}</tbody></table></div>{user?.rol==='ADMIN'&&<button className="btn btn-primary" disabled={busy||isReadOnly||active.estado!=='FINALIZADO'||!preview.rows.length||preview.rows.some((r:any)=>r.errores.length)} onClick={()=>{if(window.confirm('¿Aplicar este conteo revisado al inventario?'))void action(async()=>{await api.post(`/levantamientos/${activeId}/aplicar`,{token:preview.token});setPreview(null);});}}>Aplicar al inventario</button>}</section>}
  </>}
 </main></div>;
};
